name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Page Speed Insights (Mobile)
      uses: JakePartusch/psi-action@v1
      with:
        url: https://sad-wozniak-6465c2.netlify.com
        threshold: 90
        strategy: mobile
    - name: Page Speed Insights (Desktop)
      uses: JakePartusch/psi-action@v1
      with:
        url: https://sad-wozniak-6465c2.netlify.com
        threshold: 90
        strategy: Desktop