name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Page Speed Insights (Mobile)
      uses: JakePartusch/psi-action@v1
      with:
        url: https://thirsty-cori-5d6045.netlify.com
        threshold: 90
        strategy: mobile
    - name: Page Speed Insights (Desktop)
      uses: JakePartusch/psi-action@v1
      with:
        url: https://thirsty-cori-5d6045.netlify.com
        threshold: 90
        strategy: Desktop

